name: Scheduled Health Check

# Controls when the action will run.
on:
  #schedule:
  # - cron: "*/5 * * * *"
  push:
    branches:
      - main

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
      - name: Run python script
        id: shell_script_run
        run: |
          bash logrotate.sh
          python3 req.py
          git config --global user.name 'tuarjun'
          git config --global user.email 'tuar@protonmail.com'
          git add -A --force logs/
          git commit -am '[Automated] Update Health Check Logs'
          git push

